name: Deploy to GitHub Pages

# Trigger deployment on push to main branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
      
      - name: Enable web
        run: flutter config --enable-web
        working-directory: FProjects/BuyBackTools
        
      - name: Get dependencies
        run: flutter pub get
        working-directory: FProjects/BuyBackTools
        
      - name: Create secrets.dart
        run: |
          cat > FProjects/BuyBackTools/lib/secrets.dart <<EOF
          const String googleSheetsApiKey = '${{ secrets.GOOGLE_SHEETS_API_KEY }}';
          const String API_KEY = '${{ secrets.API_KEY }}';
          EOF
        
      - name: Build web
        run: flutter build web --release --web-renderer canvaskit --base-href /
        working-directory: FProjects/BuyBackTools
        
      - name: Configure custom domain
        run: echo "itscrazyamazing.com" > FProjects/BuyBackTools/build/web/CNAME
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: FProjects/BuyBackTools/build/web
          commit_message: "Deploy web app" 